Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c8e23f950c7725b9
      Tags:
       - key: "name"
         Value: !Join ["-",[my, inst, from , cloudformation]]